# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test-paramsAPI:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Step 3 - Run unit tests for paramsAPI
        working-directory: paramsAPI
        run: |
          echo "Loading... Running unit tests for paramsAPI"
          mvn clean verify -Dtest=*IT

      - name: Step 4 - Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-paramsAPI
          path: paramsAPI/target/surefire-reports

      - name: Step 5 - Upload code coverage reports for paramsAPI
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report-paramsAPI
          path: paramsAPI/target/site/jacoco/index.html

  build-and-assemble-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Step 3 - Build and assemble modules
        run: |
          echo "Loading... Building and assembling modules"
          mvn clean install -DskipTests -P assemble-modules
