# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Clean and Build
      run: mvn clean install -DskipTests
      
    - name: Checkstyle
      run: mvn checkstyle:checkstyle
      
    - name: Project Test
      run: mvn test -Dtest=*IT
      
    - name: Code Coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        flags: unittests
      
    - name: Build with Maven
      run: mvn -B package -DskipTests -Pprod --file pom.xml
    